server:
    port: 8222

spring:
    kafka:
        bootstrap: localhost:9092
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
    config:
        import: secrets-dev.properties
    flyway:
      enabled: true
      url: jdbc:postgresql://localhost:5433/notification_db
      password: root
      user: admin
      schemas: public
      locations: classpath:db/migration/notification_db
      baseline-on-migrate: true
      baseline-version: '0'
          