server:
    port: 8222

spring:
    kafka:
        bootstrap: localhost:9092
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate
    config:
        import: secrets-prod.properties
