server:
    port: 8222

spring:
    kafka:
        bootstrap: localhost:9092
    mail:
        host: smtp.gmail.com
        port: 587
        username: 
        password:
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
            