server:
  port: 9002

spring:
    application:
        name: user-service
    datasource:
        username: admin
        password: root
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/user_db
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
 